### ISSUE TITLE
[백엔드] 요구사항 

### ISSUE THREAD

**Issue by ghdcksgml1** [winter-soft/eatda-client#1]
* [ ] - 장바구니 보여줄때 menuCheck true인 것만 출력하도록 설정해주세요.

**Comment by ghdcksgml1** [comment]
구지원 닦달 이슈 ㅋㅋㅋㅋㅋㅋ

**Comment by ghdcksgml1** [comment]
- OrderDetail (장바구니) 에서 menuCheck 컬럼을 현재 장바구니에 들어있는 메뉴가 true가 되도록 용도를 변경했습니다.
- 그리고 만약 장바구니에 들어있던 메뉴들과 다른 가게의 메뉴가 들어오게 될 경우, 기존 장바구니를 싹 삭제하고 새로운 메뉴를 넣도록 설정했습니다.

https://github.com/ghdcksgml1/swhackathon-backend/issues/22

**Comment by ghdcksgml1** [comment]
## ⭐️ 딜(Order)을 메인화면에서 보여줄때 

### 오더를 추가할때

제 생각에는 딜을 생성할때 날짜와 점심, 저녁을 선택할 수 있게 설정해서 formData로 넘겨주면

백엔드에서 dealTime 이라는 LocalDateTime 형태의 컬럼에 값을 저장해두고,

### 오더를 필터링할때

프론트에서 오늘 점심, 오늘 저녁, 내일 점심, 내일 저녁 탭을 클릭할때 

현재 시간을 기준으로 오늘 점심이면 ( 오늘 날짜계산 + 11:00 ) 이런식으로 필터조건을 넣어서 호출하는 방식은 어떨까요?  **( 1 )**

(오늘 점심 = 1, 오늘 저녁 = 2, 내일 점심 = 3, 내일 저녁 = 4) 같은 방식으로 넘겨주면 백엔드에서 작업 가능할것같기도..  **( 2 )**

<br/><br/>

내일 저녁이 오늘 저녁이 될수도 있는 부분이라 시간값을 저장해두는게 좋을 것 같아서 코멘트 남깁니다.

**Comment by ghdcksgml1** [comment]
시간탭 추가 완료했어요. URL은 
```
http://api-eatda.wintersoft.kr/api/order/{destinationId}/{timeIndex}
```

입니다.  이슈 들어가보면 결과사진 있어요.

https://github.com/ghdcksgml1/swhackathon-backend/issues/21

**Comment by ITKOO** [comment]
넵 확인했습니다
회의 때 이야기한 아래 내용 이슈 생성해서
이 이슈는 close 처리 하겠습니다~

1. (백엔드)시간대 / 장소별로 오더 조회할 수 있는 api 요청
2. (프론트) 1번 적용
3. (프론트) 메뉴 여러개 담을 수 있도록 수정
